### ISSUE TITLE
$ref containing external filename

### ISSUE THREAD

**Issue by jayvdb** [adwhit/hsr#12]
e.g. input

```yaml
components:
  schemas:
    CartesianCoordinate:
      $ref: "./schemas/CartesianCoordinate.yaml"
```
Most Rust openAPI readers have this problem, but https://github.com/kstasik/schema-tools has solved it, and has a CLI command to convert such an OpenAPI into a single YAML file without external references.
